# Generated by Django 2.2 on 2019-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('memory_load', models.FloatField()),
                ('cpu_load', models.FloatField()),
                ('num_processes', models.IntegerField()),
                ('num_apps', models.IntegerField()),
                ('memory_intake', models.FloatField()),
            ],
        ),
    ]
