# Generated by Django 2.2 on 2019-04-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='servername',
            field=models.CharField(default='Server 1', max_length=50),
        ),
    ]
